site_name: pyECS

theme:
  name: material

nav:
  - Home: index.md
  - API:
    - Distributor: api/distributor.md
    - Commands: api/commands.md
    - System: api/system.md
    - Entity: api/entity.md
    - Component: api/component.md
  - About: about.md
  - License: license.md
