site_name: EnCoSy

theme:
  name: material

plugins:
- mkdocstrings:
    handlers:
      python:
        paths:
          - ./encosy

nav:
  - Home: index.md
  - API:
    - Control Panel: api/control_panel.md
    - Types: api/typings.md
    - Runner: api/runner.md
    - Storage:
      - System: api/system.md
      - Entity: api/entity.md
      - Resource: api/resource.md
  - About: about.md
  - License: license.md
